name = "three-router-with-bgp"
allow_software_emulation = true

[[routers]]
name = "R01"
version = "7.23.1"
memory_mib = 384
cpus = 1
bootstrap = [
  "/system/identity/set name=R1",
  "/ip/address/add address=192.0.2.1/30 interface=ether2",
  "/routing/bgp/instance/add name=scenario as=65001 router-id=10.0.0.1",
  "/routing/bgp/connection/add name=R1-R2 instance=scenario remote.address=192.0.2.2 remote.as=65002 local.role=ebgp",
]

[[routers]]
name = "R02"
version = "7.23.1"
memory_mib = 384
cpus = 1
bootstrap = [
  "/system/identity/set name=R2",
  "/ip/address/add address=192.0.2.2/30 interface=ether2",
  "/ip/address/add address=192.0.2.5/30 interface=ether3",
  "/routing/bgp/instance/add name=scenario as=65002 router-id=10.0.0.2",
  "/routing/bgp/connection/add name=R2-R1 instance=scenario remote.address=192.0.2.1 remote.as=65001 local.role=ebgp",
  "/routing/bgp/connection/add name=R2-r3 instance=scenario remote.address=192.0.2.6 remote.as=65003 local.role=ebgp",
]

[[routers]]
name = "R03"
version = "7.23.1"
memory_mib = 384
cpus = 1
bootstrap = [
  "/system/identity/set name=R3",
  "/ip/address/add address=192.0.2.6/30 interface=ether2",
  "/routing/bgp/instance/add name=scenario as=65003 router-id=10.0.0.3",
  "/routing/bgp/connection/add name=r3-R2 instance=scenario remote.address=192.0.2.5 remote.as=65002 local.role=ebgp",
]

[[links]]
a = "R01:ether2"
b = "R02:ether2"

[[links]]
a = "R02:ether3"
b = "R03:ether2"
